[[Application-API]]
== Application API

[[Application-생성]]
=== Application 생성
operation::application-controller-test/신청서_생성[snippets='http-request,request-parts,http-response,response-headers']

[[Application-단일-조회]]
=== Application 단일 조회
operation::application-controller-test/신청서_조회[snippets='http-request,path-parameters,http-response,response-fields']

[[Application-리스트-조회]]
=== Application 리스트 조회
operation::application-controller-test/신청서_리스트_조회[snippets='http-request,query-parameters,http-response,response-fields']

[[Application-수정]]
=== Application 수정
operation::application-controller-test/신청서_수정[snippets='http-request,path-parameters,request-parts,http-response,response-headers']

[[Application-상태-수정]]
=== Application 상태 수정
operation::application-controller-test/신청서_상태_수정[snippets='http-request,path-parameters,request-parts,http-response,response-headers']

[[Application-삭제]]
=== Application 삭제
operation::application-controller-test/신청서_삭제[snippets='http-request,path-parameters,request-parts,http-response,response-headers']
